sudo: required

services:
  - docker

language: node_js

node_js:
  - "6"

install:
  - npm install -g dockerlint

env:
  - TEST_DIR=3.4
  - TEST_DIR=3.5
  - TEST_DIR=edge

script: cd $TEST_DIR && dockerlint Dockerfile && docker build -t T_$TEST_DIR .

